server {
    listen 8080;
    root /www;
    index index.html;

    location = /powered-by-hugerte {
        return 307 /;
    }

    location = /docs/hugerte/1/changelog {
        return 302 https://github.com/hugerte/hugerte/blob/main/modules/hugerte/CHANGELOG.md;
    }

    location = /docs/hugerte/1/vite-es6-npm {
        return 302 https://github.com/hugerte/hugerte-docs/?tab=readme-ov-file#bundling;
    }

    location ~ ^/docs/hugerte/1/angular- {
        return 302 https://github.com/hugerte/hugerte-docs/blob/main/integrations/angular.md;
    }

    location ~ ^/docs/hugerte/1/ {
        try_files $uri /docs-fallback.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
